<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product')->insert([
            [
                'id' => 1,
                'category_fk' => 1,
                'title' => 'Mesa Rectangular Premium',
                'price' => 400000,
                'promo_price' => 350000,
                'release_date' => '2024-01-01',
                'description' => 'Mesa ideal para comedor familiar, con terminaciones de alta calidad y acabado hidrolaqueado.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'category_fk' => 4,
                'title' => 'Estantería Industrial Modular',
                'price' => 230000,
                'promo_price' => null,
                'release_date' => '2026-01-01',
                'description' => 'Estantería moderna para hogar u oficina con gran capacidad de almacenamiento.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'category_fk' => 2,
                'title' => 'Silla Clásica Tapizada',
                'price' => 95000,
                'promo_price' => 85000,
                'release_date' => '2025-01-06',
                'description' => 'Silla cómoda para comedor o escritorio, disponible en distintos acabados.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'category_fk' => 2,
                'title' => 'Escritorio Ejecutivo',
                'price' => 350000,
                'promo_price' => 320000,
                'release_date' => '2026-01-03',
                'description' => 'Escritorio amplio y funcional para espacios de trabajo modernos.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'category_fk' => 1,
                'title' => 'Mesa Redonda Familiar',
                'price' => 280000,
                'promo_price' => null,
                'release_date' => '2026-02-01',
                'description' => 'Diseño elegante para reuniones familiares y espacios reducidos.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'category_fk' => 2,
                'title' => 'Banco Alto de Barra',
                'price' => 75000,
                'promo_price' => 65000,
                'release_date' => '2026-02-05',
                'description' => 'Banco moderno ideal para cocinas y barras desayunadoras.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'category_fk' => 4,
                'title' => 'Biblioteca de Diseño',
                'price' => 310000,
                'promo_price' => null,
                'release_date' => '2026-02-10',
                'description' => 'Biblioteca espaciosa con múltiples compartimentos.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'category_fk' => 3,
                'title' => 'Rack para Televisor',
                'price' => 180000,
                'promo_price' => 160000,
                'release_date' => '2026-02-15',
                'description' => 'Rack funcional con espacio para consolas y accesorios.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'category_fk' => 3,
                'title' => 'Mesa Ratona Minimalista',
                'price' => 120000,
                'promo_price' => null,
                'release_date' => '2026-02-20',
                'description' => 'Mesa de centro moderna para living contemporáneo.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'category_fk' => 2,
                'title' => 'Silla Ergonómica',
                'price' => 110000,
                'promo_price' => 95000,
                'release_date' => '2026-02-25',
                'description' => 'Diseñada para brindar comodidad durante largas jornadas.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'category_fk' => 1,
                'title' => 'Mesa Extensible',
                'price' => 450000,
                'promo_price' => 399000,
                'release_date' => '2026-03-01',
                'description' => 'Mesa adaptable para diferentes cantidades de comensales.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'category_fk' => 4,
                'title' => 'Estantería Compacta',
                'price' => 145000,
                'promo_price' => null,
                'release_date' => '2026-03-05',
                'description' => 'Perfecta para departamentos y oficinas pequeñas.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'category_fk' => 3,
                'title' => 'Mueble Organizador',
                'price' => 210000,
                'promo_price' => 190000,
                'release_date' => '2026-03-10',
                'description' => 'Solución práctica para almacenamiento y decoración.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'category_fk' => 2,
                'title' => 'Banqueta Moderna',
                'price' => 68000,
                'promo_price' => null,
                'release_date' => '2026-03-15',
                'description' => 'Banqueta versátil para distintos ambientes.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'category_fk' => 1,
                'title' => 'Mesa de Reuniones',
                'price' => 520000,
                'promo_price' => 470000,
                'release_date' => '2026-03-20',
                'description' => 'Ideal para oficinas y espacios colaborativos.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'category_fk' => 3,
                'title' => 'Aparador Contemporáneo',
                'price' => 340000,
                'promo_price' => null,
                'release_date' => '2026-03-25',
                'description' => 'Aparador elegante con amplio espacio de guardado.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'category_fk' => 4,
                'title' => 'Biblioteca Modular',
                'price' => 295000,
                'promo_price' => 270000,
                'release_date' => '2026-04-01',
                'description' => 'Biblioteca adaptable a diferentes configuraciones.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'category_fk' => 2,
                'title' => 'Silla de Comedor Premium',
                'price' => 130000,
                'promo_price' => null,
                'release_date' => '2026-04-05',
                'description' => 'Diseño elegante y confortable para uso diario.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'category_fk' => 3,
                'title' => 'Mesa Auxiliar Decorativa',
                'price' => 89000,
                'promo_price' => 79000,
                'release_date' => '2026-04-10',
                'description' => 'Complemento ideal para living, dormitorio u oficina.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
