<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product')->insert([
            [
                'id' => 1,
                'category_fk' => 1,
                'title' => 'Mesa Rectangular Premium',
                'price' => 70000000,
                'promo_price' => 40000000,
                'release_date' => '2024-01-01',
                'description' => 'Mesa ideal para comedor familiar, con terminaciones de alta calidad y acabado hidrolaqueado.',
                'img' => 'products/mesarectangularpremium.png',
                'img_description' => 'Mesa Rectangular Premium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'category_fk' => 4,
                'title' => 'Estantería Industrial Modular',
                'price' => 35000000,
                'promo_price' => null,
                'release_date' => '2026-01-01',
                'description' => 'Estantería moderna para hogar u oficina con gran capacidad de almacenamiento.',
                'img' => 'products/estanteriaindustrialmodular.png',
                'img_description' => 'Estantería Industrial Modular',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'category_fk' => 2,
                'title' => 'Silla Clásica Tapizada',
                'price' => 30000000,
                'promo_price' => 25000000,
                'release_date' => '2025-01-06',
                'description' => 'Silla cómoda para comedor o escritorio, disponible en distintos acabados.',
                'img' => 'products/sillaclasicatapizada.png',
                'img_description' => 'Silla Clásica Tapizada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'category_fk' => 2,
                'title' => 'Escritorio Ejecutivo',
                'price' => 40000000,
                'promo_price' => 32000000,
                'release_date' => '2026-01-03',
                'description' => 'Escritorio amplio y funcional para espacios de trabajo modernos.',
                'img' => 'products/escritorioejecutivo.png',
                'img_description' => 'Escritorio Ejecutivo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'category_fk' => 1,
                'title' => 'Mesa Redonda Familiar',
                'price' => 28000000,
                'promo_price' => null,
                'release_date' => '2026-02-01',
                'description' => 'Diseño elegante para reuniones familiares y espacios reducidos.',
                'img' => 'products/mesaredondafamiliar.png',
                'img_description' => 'Mesa Redonda Familiar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'category_fk' => 2,
                'title' => 'Banco Alto de Barra',
                'price' => 5000000,
                'promo_price' => 4000000,
                'release_date' => '2026-02-05',
                'description' => 'Banco moderno ideal para cocinas y barras desayunadoras.',
                'img' => 'products/bancoaltodebarra.png',
                'img_description' => 'Banco Alto de Barra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'category_fk' => 4,
                'title' => 'Biblioteca de Diseño',
                'price' => 35000000,
                'promo_price' => null,
                'release_date' => '2026-02-10',
                'description' => 'Biblioteca espaciosa con múltiples compartimentos.',
                'img' => 'products/bibliotecadediseno.png',
                'img_description' => 'Biblioteca de Diseño',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'category_fk' => 3,
                'title' => 'Rack para Televisor',
                'price' => 40000000,
                'promo_price' => 32000000,
                'release_date' => '2026-02-15',
                'description' => 'Rack funcional con espacio para consolas y accesorios.',
                'img' => 'products/rackparatelevisor.png',
                'img_description' => 'Rack para Televisor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'category_fk' => 3,
                'title' => 'Mesa Ratona Minimalista',
                'price' => 27000000,
                'promo_price' => null,
                'release_date' => '2026-02-20',
                'description' => 'Mesa de centro moderna para living contemporáneo.',
                'img' => 'products/mesaratonaminimalista.png',
                'img_description' => 'Mesa Ratona Minimalista',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'category_fk' => 2,
                'title' => 'Silla Ergonómica',
                'price' => 18000000,
                'promo_price' => 15000000,
                'release_date' => '2026-02-25',
                'description' => 'Diseñada para brindar comodidad durante largas jornadas.',
                'img' => 'products/sillaergonomica.png',
                'img_description' => 'Silla Ergonómica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'category_fk' => 1,
                'title' => 'Mesa Extensible',
                'price' => 30000000,
                'promo_price' => 28000000,
                'release_date' => '2026-03-01',
                'description' => 'Mesa adaptable para diferentes cantidades de comensales.',
                'img' => 'products/mesaextensible.png',
                'img_description' => 'Mesa Extensible',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'category_fk' => 4,
                'title' => 'Estantería Compacta',
                'price' => 7000000,
                'promo_price' => null,
                'release_date' => '2026-03-05',
                'description' => 'Perfecta para departamentos y oficinas pequeñas.',
                'img' => 'products/estanteriacompacta.png',
                'img_description' => 'Estantería Compacta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'category_fk' => 3,
                'title' => 'Mueble Organizador',
                'price' => 21000000,
                'promo_price' => 19000000,
                'release_date' => '2026-03-10',
                'description' => 'Solución práctica para almacenamiento y decoración.',
                'img' => 'products/muebleorganizador.png',
                'img_description' => 'Mueble Organizador',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'category_fk' => 2,
                'title' => 'Banqueta Moderna',
                'price' => 7500000,
                'promo_price' => null,
                'release_date' => '2026-03-15',
                'description' => 'Banqueta versátil para distintos ambientes.',
                'img' => 'products/banquetamoderna.png',
                'img_description' => 'Banqueta Moderna',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'category_fk' => 1,
                'title' => 'Mesa de Reuniones',
                'price' => 51000000,
                'promo_price' => 48000000,
                'release_date' => '2026-03-20',
                'description' => 'Ideal para oficinas y espacios colaborativos.',
                'img' => 'products/mesadereuniones.png',
                'img_description' => 'Mesa de Reuniones',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'category_fk' => 3,
                'title' => 'Cómoda moderna',
                'price' => 37000000,
                'promo_price' => null,
                'release_date' => '2026-03-25',
                'description' => 'Cómoda elegante con amplio espacio de guardado.',
                'img' => 'products/aparadorcontemporaneo.png',
                'img_description' => 'Cómoda moderna',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'category_fk' => 4,
                'title' => 'Biblioteca Modular',
                'price' => 28000000,
                'promo_price' => 26000000,
                'release_date' => '2026-04-01',
                'description' => 'Biblioteca adaptable a diferentes configuraciones.',
                'img' => 'products/bibliotecamodular.png',
                'img_description' => 'Biblioteca Modular',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'category_fk' => 2,
                'title' => 'Silla de Comedor Premium',
                'price' => 9000000,
                'promo_price' => null,
                'release_date' => '2026-04-05',
                'description' => 'Diseño elegante y confortable para uso diario.',
                'img' => 'products/silladecomedorpremium.png',
                'img_description' => 'Silla de Comedor Premium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'category_fk' => 3,
                'title' => 'Mesa Auxiliar Decorativa',
                'price' => 6500000,
                'promo_price' => 5500000,
                'release_date' => '2026-04-10',
                'description' => 'Complemento ideal para living, dormitorio u oficina.',
                'img' => 'products/mesaauxiliardecorativa.png',
                'img_description' => 'Mesa Auxiliar Decorativa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
